pom.xml
src/main/scala/fi/vm/sade/valintatulosservice/SecuritySettings.scala
src/main/scala/fi/vm/sade/valintatulosservice/config/AppConfig.scala
src/test/scala/fi/vm/sade/security/CasClientIntegrationTester.scala
src/test/scala/fi/vm/sade/security/LdapClientIntegrationTester.scala
src/test/scala/fi/vm/sade/security/TicketPuller.scala
src/test/scala/fi/vm/sade/valintatulosservice/local/ValintaTulosServletSpec.scala

Reverts Opetushallitus/valinta-tulos-service#3

Revert "New scala utils"

---

valinta-tulos-service/src/main/resources/fixtures/sijoittelu/varalla-julkaistu-peruuntunut.json
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValintatulosService.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValintatulosServiceSpec.scala

Check peruuntunut -> kesken after applying korkeakoulusäännöt

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValintatulosService.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValintatulosServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/domain/Hakemuksentulos.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/VastaanottoServiceHakijanaSpec.scala

Because schools need them through hakeneet interface

Publish results earlier for sure

---

valinta-tulos-service/src/main/scala/ScalatraBootstrap.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/json/StreamingJsonArrayRetriever.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/DirectMongoLatestSijoitteluAjoClient.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/LatestSijoitteluAjoClient.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/SijoittelutulosService.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/MailPollerSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValintatulosServiceLisahakuSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValintatulosServiceSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/VastaanottoServiceHakijanaSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/VastaanottoServiceVirkailijanaSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/performance/MailPollerPerformanceTester.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/performance/PollerTester.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/testenvironment/ValintatulosIntegrationTest.scala

BUG-987 : Call sijoittelu API for latest SijoitteluAjo

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValintatulosService.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/domain/Hakemuksentulos.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/json/HakutoiveentulosSerializer.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/json/JsonFormats.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/VastaanottoServiceVirkailijanaSpec.scala

Maybe this "multi-state" could be used in other cases too.

BUG-1029 : Show YPS state after deadline too

---

valinta-tulos-service/src/main/resources/db/migration/V23__unique_index_for_vastaanotot.sql

Henkilo should not have two non-deleted vastaanottos for same hakukohde.

Added partial unique index for vastaanotto

---

valinta-tulos-service/pom.xml
valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service-devtest.properties.template
valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service-oph.properties
valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service.properties.template
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/OphUrlProperties.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/config/OphUrlProperties.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/config/VtsAppConfig.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/config/VtsApplicationSettings.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/config/VtsOphUrlProperties.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/json/StreamingJsonArrayRetriever.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/migraatio/vastaanotot/MissingHakijaOidResolver.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ohjausparametrit/OhjausparametritService.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/SijoittelunTulosRestClient.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/StreamingHakijaDtoClient.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/config/VtsOphUrlPropertiesTest.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/testenvironment/OhjausparametritIntegrationTest.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/testenvironment/TarjontaIntegrationTest.scala
valinta-tulos-valintarekisteri-db/pom.xml
valinta-tulos-valintarekisteri-db/src/main/resources/oph-configuration/valinta-tulos-service-devtest.properties.template
valinta-tulos-valintarekisteri-db/src/main/resources/oph-configuration/valinta-tulos-service.properties.template
valinta-tulos-valintarekisteri-db/src/main/resources/oph-configuration/valinta-tulos-valintarekisteri-db-oph.properties
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/config/ValintarekisteriAppConfig.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/config/ValintarekisteriApplicationSettings.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/tarjonta/HakuService.scala

Sec 6 csrf

---

valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service.properties.template
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValintatulosService.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/json/StreamingJsonArrayRetriever.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/HakijaDtoMongoClient.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/config/ValintarekisteriApplicationSettings.scala

Haetaan isojen hakujen (keväät 2015-2017) valintatulokset suoraan mongosta sijoittelu-servicen sijaan.

Bug 1334 odw hakemukset

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/migraatio/vastaanotot/MissingHakijaOidResolver.scala

Hetuttomat hakijat aihettavat classcastexceptionin kun valinnan tuloksia haetaan ODWhen.

BUG-1346: Hetu is not mandatory for hakija.

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/SijoitteluServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/VtsServletBase.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/SijoitteluServletSpec.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/SijoitteluRepository.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/domain/NotFoundException.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/sijoittelu/ConstructSijoitteluajonHakukohde.scala
valinta-tulos-valintarekisteri-db/src/test/scala/fi/vm/sade/valintatulosservice/valintarekisteri/sijoittelu/ValintarekisteriForSijoitteluSpec.scala

Return 404 Not Found instead of 400 Bad Request when results are not found.
Then we can handle it more gracefully in the UI (see https://github.com/Opetushallitus/valintaperusteet/pull/123 )

HK-6 : ei sijoittelun tulosta

---

valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/domain/valinnantulos.scala

Also includes setting ehdollisenHyvaksymisenEhto* fields

Use Valintatulos constructor to avoid generating extra log entries

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/valinnantulos/ErillishaunValinnantulosStrategy.scala

For very lax definitions of "Implement" :)

Implement missing entry in possible transformation

---

valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service-devtest.properties.template
valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service.properties.template
valinta-tulos-service/src/main/scala/ScalatraBootstrap.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/security/VtsAuthenticatingClient.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/KelaHealthCheckServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/SecuritySettings.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/audit.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/config/VtsAppConfig.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/kela/Vastaanotto.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/kela/VtsKelaAuthenticatingClientMock.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/kela/VtsKelaAuthenticationClient.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/kela/VtsKelaSessionCookie.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/migraatio/vastaanotot/MissingHakijaOidResolver.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/JonoFinder.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/vastaanottomeili/MailPollerAdapter.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/SharedJetty.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/KelaHealthCheckServletSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/KelaKoulutusSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/production/SijoitteluRestTest.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/production/SijoittelunOsatRestTest.scala
valinta-tulos-valintarekisteri-db/src/main/resources/db/migration/V76__hakijaryhman_hakemukset_hakemus_oid_idx.sql
valinta-tulos-valintarekisteri-db/src/main/resources/db/migration/V77__jonosijat_sijoitteluajo_id_hakemus_oid_idx.sql
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/tarjonta/KelaKoulutus.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/MailPollerRepository.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/MailPollerRepositoryImpl.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/ValinnantulosRepositoryImpl.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/domain/valinnantulos.scala

Lisätietoa: https://jira.oph.ware.fi/jira/browse/OK-153

Jira OK-153: Kela reaalirajapinta healtcheck

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValinnantulosService.scala

Because vastaanottotila is part of Valinnantulos, UIs currently send
OTTANUT_VASTAAN_TOISEN_PAIKAN if that is the current vastaanottotila.
VastaanottoService::vastaanotaVirkailijana does not do change detection
and throws if given OTTANUT_VASTAAN_TOISEN_PAIKAN. This fixes the
problem until vastaanottotila is stored along with the other parts of
Valinnantulos.

Don't try to store OTTANUT_VASTAAN_TOISEN_PAIKAN

---

valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/ValinnantulosRepositoryImpl.scala

etsitään deleted_vastaanotot -taulusta relevantit rivit ja esitetään käyttäjälle selventävästi "Kesken (poistettu)" -tila sekä poiston tiedot.

Bug 1495 vastaanoton poisto muutoshistoriaan

---

valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service-oph.properties
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/migraatio/vastaanotot/MissingHakijaOidResolver.scala

`createPerson`-metodin käyttö näyttäisi poistuneen commitissa https://github.com/Opetushallitus/valinta-tulos-service/commit/808cdb13abd071a4da6568afb15a515705dd36c1

KJHH-1376: Poistaa authentication-service -riippuvuudet

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/PrivateValintatulosServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/PublicValintatulosServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValintatulosServlet.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValintaTulosServletSpec.scala

Epähuomiossa koitettiin lukea parametri, jota endpointiin ei anneta.

BUG-1966 : kirjeiden muodostus epäonnistuu

---

valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service-oph.properties
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/FixtureServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/config/VtsAppConfig.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/hakemus/AtaruHakemusEnricher.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/hakemus/HakemusRepository.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/hakemus/ataruHakemusRepository.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValintaTulosServletSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/VastaanottoServiceVirkailijanaSpec.scala
valinta-tulos-valintarekisteri-db/src/main/resources/oph-configuration/valinta-tulos-valintarekisteri-db-oph.properties

Tulee asentaa vasta https://github.com/Opetushallitus/ataru/pull/841 jälkeen, älä mergeä.

Hle 928  vts hakee kaikki haun hakemukset

---

valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service-devtest.properties.template
valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service.properties.template
valinta-tulos-service/src/main/scala/ScalatraBootstrap.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/config/VtsApplicationSettings.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/hakemus/AtaruHakemusEnricher.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ohjausparametrit/OhjausparametritService.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/HakemusRepositorySpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/HakuServiceSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValinnantulosServiceVastaanottoSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValintatulosServiceLisahakuSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValintatulosServiceSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/VastaanottoServiceHakijanaSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/VastaanottoServiceVirkailijanaSpec.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/testenvironment/ValintatulosIntegrationTest.scala
valinta-tulos-valintarekisteri-db/src/main/resources/oph-configuration/valinta-tulos-service.properties.template
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/config/ValintarekisteriApplicationSettings.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/memoize/Cache.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/memoize/TTLOptionalMemoize.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/tarjonta/HakuService.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/sijoittelu/Valintarekisteri.scala
valinta-tulos-valintarekisteri-db/src/test/scala/fi/vm/sade/valintatulosservice/valintarekisteri/ITSetup.scala

Samalla kasvatetaan välimuistin maksimikokoa 32 tietueesta :D

BUG-1975 : hakukohde valimuisti hakemusten rikastamiseen

---

valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service-devtest.properties.template
valinta-tulos-service/src/main/resources/oph-configuration/valinta-tulos-service.properties.template
valinta-tulos-service/src/main/scala/ScalatraBootstrap.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/PrivateValintatulosServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/PublicValintatulosServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValintatulosServlet.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/config/VtsApplicationSettings.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/streamingresults/HakemustenTulosHakuLock.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/streamingresults/StreamingValintatulosService.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/streamingresults/HakemustenTulosHakuLockSpec.scala
valinta-tulos-valintarekisteri-db/src/main/resources/oph-configuration/valinta-tulos-service.properties.template

- jonon maksimipituus konfiguroitavaksi
- jonon maksimipituus isommaksi
- isompi timeout-arvo lukon saamiselle
- refaktorointi
- testi

BUG-1976 :  ison haun latausten jono konfiguroitavaksi

---

.travis.yml
pom.xml
valinta-tulos-henkiloviite-synchronizer/pom.xml
valinta-tulos-service/pom.xml
valinta-tulos-valintarekisteri-db/pom.xml

Käytetään valintojen riippuvuuksien uusia versioita.

VTKU-28 : dependencies upgrade

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValintatulosService.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValintatulosServiceSpec.scala

Only change state if no higher hyvaksytty julkaistu exists

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/vastaanottomeili/MailerComponent.scala

isPollingComplete only indicates whether the polling managed
to go through without hitting the timeout limit.

BUG-2019 : Do not stop sending when isPollingComplete == true

---

pom.xml
valinta-tulos-service/README.md
valinta-tulos-valintarekisteri-db/src/main/resources/db/migration-vts/V92__add_general_comments.sql
valinta-tulos-valintarekisteri-db/src/main/resources/db/migration-vts/V93__add_comments_to_sijoittelun_tulos_tables.sql

Mukana myös tarkennuksia, joilla käynnistys komentoriviltä onnistuu.

VTKU-57 : Sijoittelun tuloksen dokumentaatio tietokannassa

---

valinta-tulos-valintarekisteri-db/src/main/resources/db/migration-vts/V92__add_general_comments.sql
valinta-tulos-valintarekisteri-db/src/main/resources/db/migration-vts/V93__add_comments_to_sijoittelun_tulos_tables.sql
valinta-tulos-valintarekisteri-db/src/main/resources/db/migration-vts/V94__add_comments_to_valinnan_tulos_tables.sql

Tässä päivitetään myös kantaskeeman dokumentaatiota kannan yleiskuvauksena.

VTKU-57 : Valinnan tuloksen dokumentaatio tietokannassa

---

.travis.yml
pom.xml
valinta-tulos-henkiloviite-synchronizer/pom.xml
valinta-tulos-service/pom.xml
valinta-tulos-service/src/main/scala/ScalatraBootstrap.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/fixture/SijoitteluFixtures.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/SijoitteluServiceSpec.scala
valinta-tulos-valintarekisteri-db/pom.xml
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/HakijaRepository.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/SijoitteluRepository.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/DeleteSijoitteluRepositoryImpl.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/HakijaRepositoryImpl.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/SijoitteluRepositoryImpl.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/StoreSijoitteluRepositoryImpl.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/ValintarekisteriResultExtractors.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/domain/SijoitteluWrapper.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/domain/sijoitteluRecords.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/sijoittelu/sijoitteluajonHakija.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/sijoittelu/sijoitteluajonHakukohde.scala
valinta-tulos-valintarekisteri-db/src/test/scala/fi/vm/sade/valintatulosservice/valintarekisteri/ValintarekisteriDbTools.scala
valinta-tulos-valintarekisteri-db/src/test/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/ValintarekisteriDbReadSijoitteluSpec.scala

Katso myös https://github.com/Opetushallitus/sijoittelu/pull/5

Vtku 29 pistetiedot pois rebased

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/HyvaksynnanEhtoServlet.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/ehdollisestihyvaksyttavissa/HyvaksynnanEhtoRepositoryImpl.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/ehdollisestihyvaksyttavissa/hyvaksynnanEhtoRepository.scala

Siirtää myös olemassa olleet API:t uusiin polkuihin taaksepäinyhteensopivasti.

Koko hakukohteen ehdollisuudet palauttavat API:t

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/ValinnantulosService.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/sijoittelu/SijoittelutulosService.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/valinnantulos/ErillishaunValinnantulosStrategy.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/valinnantulosServlet.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValinnantulosServletSpec.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/ValinnantulosRepository.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/ValinnantulosRepositoryImpl.scala

Katso myös https://github.com/Opetushallitus/ataru/pull/977

Hle 1154  kevytvalinta yps

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/valinnantulos/ErillishaunValinnantulosStrategy.scala

Branchi luotu BUG-2159-haaran pohjalta. Mukana siis BUG-2159 muutokset kunnes se on mergetty masteriin.

BUG-2149: erillishaun excel import toimii oudosti

---

valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/tarjonta/HakuService.scala

This reverts commit a08b4e3671e5bc542facc3311fd8ca5d6c13f844.

Revert "Disabloitu tilapäisesti kela-rajapinnan kouta-integraatio"

---

valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/tarjonta/HakuService.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/hakukohde/HakukohdeRecordService.scala

Päätellään oidin pituudesta, kannattaako kutsua vanhaa tarjontaa vai koutaa.
Samassa haarassa aiheeseen liittymätön logitusparannus.

Oy 3190 koutakutsut

---

valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/domain/Hakemus.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/hakemus/AtaruHakemusEnricher.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/hakemus/HakemusRepository.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/oppijanumerorekisteri/oppijanumerorekisteriService.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/valinnantulos/ErillishaunValinnantulosStrategy.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/vastaanottomeili/MailPoller.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValinnantulosServiceSpec.scala

https://jira.eduuni.fi/browse/OY-4605

OY-4605: Estä valintatietojen tallennus ei-yksilöidylle hakijalle erillishaussa

---

valinta-tulos-service/src/main/scala/ScalatraBootstrap.scala
valinta-tulos-service/src/main/scala/fi/vm/sade/valintatulosservice/valinnantulosServlet.scala
valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/local/ValinnantulosServletSpec.scala

Enableri atarun muutokselle https://github.com/Opetushallitus/ataru/pull/1511

OY-4421: Lisää deadlinet yksittäisen hakemuksen valinnantuloksiin

---

valinta-tulos-service/src/test/scala/fi/vm/sade/valintatulosservice/mock/RunBlockingMock.scala
valinta-tulos-valintarekisteri-db/src/main/scala/fi/vm/sade/valintatulosservice/valintarekisteri/db/impl/ValintarekisteriRepository.scala

Lisätty retry kanta operaatioille

Oy 4716 Kevytvalinnassa voi muokata valinnan tiloja liian nopeasti
